/* Remote Pilot Lab: complete study bank for source pages 01–42. */
(() => {
  "use strict";

  const sources = {};
  for (let page = 1; page <= 42; page += 1) {
    const number = String(page).padStart(2, "0");
    sources[`book-${number}`] = { label: `Book · source image ${number}` };
  }
  Object.assign(sources, {
    "faa-part107": { label: "FAA · Part 107 overview", url: "https://www.faa.gov/newsroom/small-unmanned-aircraft-systems-uas-regulations-part-107" },
    "faa-pilot": { label: "FAA · Become a Drone Pilot", url: "https://www.faa.gov/uas/commercial_operators/become_a_drone_pilot" },
    "faa-accident": { label: "FAA · Accident reporting", url: "https://www.faa.gov/faq/when-do-i-need-report-accident" },
    "faa-laanc": { label: "FAA · LAANC", url: "https://www.faa.gov/uas/getting_started/laanc" },
    "faa-people": { label: "FAA · Operations Over People", url: "https://www.faa.gov/uas/commercial_operators/operations_over_people" },
    "faa-waivers": { label: "FAA · Part 107 waivers", url: "https://www.faa.gov/uas/commercial_operators/part_107_waivers" },
    "faa-recreation": { label: "FAA · Recreational flyers", url: "https://www.faa.gov/uas/recreational_flyers" },
    "faa-register": { label: "FAA · Registration and Remote ID", url: "https://www.faa.gov/uas/getting_started/register_drone" }
  });

  const figures = {
    configurations: ["assets/books/complete-remote-pilot/page-05-aircraft-configurations.jpg", "Quadcopter, fixed-wing, and hexacopter configurations"],
    components: ["assets/books/complete-remote-pilot/page-06-flight-controller.jpg", "Exploded quadcopter component diagram labeled A through I"],
    controller: ["assets/books/complete-remote-pilot/page-08-remote-controller.jpg", "Mode 2 remote controller with labeled sticks and trim controls"],
    axes: ["assets/books/complete-remote-pilot/page-10-aircraft-components.jpg", "Flight controls, roll, pitch, yaw, and aircraft axes"],
    pattern: ["assets/books/complete-remote-pilot/page-13-traffic-pattern.jpg", "Complete traffic-pattern figure with the left border, base leg, and note"],
    publications: ["assets/books/complete-remote-pilot/page-14-faa-publications.jpg", "Federal Aviation Regulations and AIM publications"],
    laanc: ["assets/books/complete-remote-pilot/page-24-airspace-diagram.jpg", "FAA UAS Data Exchange and LAANC diagram"],
    notams: ["assets/books/complete-remote-pilot/page-28-vfr-sectional-chart.jpg", "Airport diagram and NOTAM keyword examples"],
    meridiansDiagram: ["assets/books/complete-remote-pilot/diagram-meridians-parallels.svg", "Original schematic globe showing meridians (longitude) and parallels (latitude)"],
    airspaceClasses: ["assets/books/complete-remote-pilot/diagram-airspace-classes.svg", "Original schematic cross-section of Class A through G airspace stacked over sample airports"],
    classDCutout: ["assets/books/complete-remote-pilot/diagram-class-d-cutout.svg", "Original schematic of a Class D cutout excluding a nearby non-tower airport"],
    windCorrection: ["assets/books/complete-remote-pilot/diagram-wind-correction.svg", "Original schematic vector triangle showing true heading, wind, and resulting ground track"]
  };

  // page, topic, prompt, answer, three distractors, explanation, optional figure, optional current FAA verification
  const rows = [
    [1,"History","What event does the book present as an early uncrewed aerial mission in 1849?","Austrian balloons carrying explosives during the siege of Venice",["Langley's Aerodrome flight","Project Aphrodite","The first Predator mission"],"It was an early mission-oriented use of an aerial system, though unlike a modern controllable drone."],
    [1,"History","Who launched the uncrewed Aerodrome from a floating barge in 1896?","Samuel Langley",["Nikola Tesla","Wilbur Wright","Igor Sikorsky"],"Langley's aircraft was catapult-launched from a barge."],
    [1,"History","During which conflict did guided, pilotless winged aircraft first fly?","World War I",["The U.S. Civil War","World War II","The Vietnam War"],"Some served as targets; bomb-carrying versions were called aerial torpedoes."],
    [1,"History","How did Germany's V-1 guidance concept terminate powered flight near the target?","It cut the engine when the system estimated it had reached the target area",["A pilot parachuted out","GPS commanded a precision landing","A radar controller recovered it"],"The V-1 used a comparatively simple guidance concept."],
    [1,"History","What was Project Aphrodite?","A U.S. effort to convert crewed B-17s into remotely controlled flying bombs",["An agricultural mapping program","A weather-satellite project","A drone-registration system"],"Pilots handled takeoff and arming, transferred control, and then parachuted from the aircraft."],

    [2,"History","Who demonstrated radio control of an object in 1898?","Nikola Tesla",["Samuel Langley","Glenn Curtiss","Robert Goddard"],"Radio control later became fundamental to remotely piloted aircraft."],
    [2,"History","What development helped create the hobby radio-control market in the 1950s?","Gas- and battery-powered remote-control aircraft",["Satellite navigation","Digital sectional charts","Part 107 certificates"],"Falling component costs and improving batteries later widened access further."],
    [2,"History","By what year does the book say remote-controlled helicopters existed?","1968",["1903","1941","1994"],"This was part of the parallel development of hobby remote-control aviation."],
    [2,"Applications","Which example best illustrates precision-agriculture use of a UAS?","Using sensors to identify crops needing water, fertilizer, or pest treatment",["Broadcasting ATIS","Inspecting pilot certificates","Issuing NOTAMs"],"Modern UAS can carry specialized sensors, not just cameras."],
    [2,"Language","Why must a remote pilot learn aviation terms and abbreviations?","To communicate accurately and understand operational information",["To avoid all contact with ATC","To replace preflight planning","To make a UAS legally airworthy"],"Shared terminology matters when working with operators, pilots, and air traffic personnel."],

    [3,"Language","What is an Advisory Circular (AC)?","FAA guidance that explains subjects beyond concise regulatory text",["A temporary flight restriction","A pilot certificate","An airport weather observation"],"ACs are generally explanatory and non-regulatory, although operationally important."],
    [3,"Weather","What does an AIRMET communicate?","A current or forecast weather hazard relevant especially to smaller aircraft",["An aircraft registration number","A permanent airspace boundary","An airport construction permit"],"Examples include turbulence, strong winds, and reduced visibility over an area."],
    [3,"Aerodynamics","What is angle of attack?","The angle between an airfoil's chord line and the relative wind",["The angle between true and magnetic north","The bank angle alone","The camera's angle below the horizon"],"It applies to wings and rotor blades and strongly affects lift."],
    [3,"Airspace","What is ATC's core function?","Separating and organizing aircraft in controlled airspace",["Certifying batteries","Publishing local property laws","Repairing airport runways"],"Remote pilots may need authorization or coordination in specific situations."],
    [3,"Airport operations","What does ATIS provide?","A continuous broadcast of non-control airport information, including weather",["A remote-pilot practical test","A list of registered drones","An aircraft control link"],"It provides routine information without congesting control frequencies."],
    [3,"Language","What does BVLOS mean?","The aircraft is operated beyond the pilot's or observer's visual line of sight",["The aircraft is below visible low overcast","The battery voltage is low","The flight is beneath controlled airspace"],"Ordinary Part 107 operations require VLOS unless appropriate FAA authority allows otherwise."],
    [3,"Remote ID","What is a FRIA?","An FAA-Recognized Identification Area where eligible aircraft may operate without broadcasting Remote ID",["A restricted military area","An airport traffic pattern","A weather product"],"FRIAs are generally sponsored by recognized organizations or educational institutions."],
    [3,"Airspace","What does LAANC provide?","A way to request eligible controlled-airspace authorization through approved services",["A replacement for a pilot certificate","Automatic obstacle avoidance","A weather forecast for every airport"],"It connects operators, service suppliers, FAA data, and air traffic facilities.",null,"faa-laanc"],

    [4,"Operating roles","Who is the remote PIC?","The person responsible for and holding final authority over the UAS operation",["Anyone watching the flight","Only the aircraft owner","The nearest controller"],"The remote PIC need not be the person physically moving the control sticks."],
    [4,"Remote ID","What is Remote Identification?","The ability of a drone in flight to broadcast required identification and location information",["A visual-observer hand signal","A weather radar mode","An airport badge"],"Requirements depend on the aircraft and operation; check current FAA guidance.",null,"faa-register"],
    [4,"Language","What is the difference between UA and UAS?","UA is the aircraft; UAS is the aircraft plus its associated operating system",["UA is civilian and UAS military","UA is fixed-wing and UAS rotor-wing","There is never a difference"],"The system can include controllers, links, sensors, processors, and other components."],
    [4,"Airport operations","What is the difference between a runway and a taxiway?","A runway is for takeoff and landing; a taxiway connects movement areas",["A taxiway is airborne","A runway is always grass","A taxiway is only for UAS"],"Charts often abbreviate them RWY and TWY."],
    [4,"Weather","How do AIRMETs and SIGMETs differ in general significance?","SIGMETs address more severe hazards broadly; AIRMETs often concern hazards especially relevant to lighter aircraft",["AIRMETs are permanent","SIGMETs apply only on the ground","They are registration categories"],"Both are area-based aviation weather advisories."],
    [4,"Time","What is UTC in aviation?","A global standard time based on Greenwich, shown in 24-hour format",["Local daylight time","A control frequency","A cloud-clearance unit"],"UTC is also called Zulu time and is used in weather and NOTAMs."],
    [4,"Operating rules","What does VLOS mean operationally?","Seeing the aircraft with unaided vision other than corrective lenses",["Seeing only its camera feed","Tracking it only on a map","Using binoculars throughout"],"VLOS supports awareness of attitude, location, direction, and hazards."],
    [4,"Weather","What is the difference between a METAR and a TAF?","A METAR reports observed airport weather; a TAF forecasts airport weather",["A METAR is a chart and a TAF a regulation","A METAR is military only","A TAF reports maintenance"],"Both use standardized coded aviation weather formats."],

    [5,"Aircraft types","What are the two primary aircraft categories described?","Fixed-wing and rotor-wing",["Crewed and satellite","IFR and VFR","Public and private"],"Fixed-wing aircraft use wings; rotor-wing aircraft use rotors for lift.","configurations"],
    [5,"Aircraft types","What defines a quadcopter?","A multicopter with four lifting rotors",["A fixed-wing aircraft with four wings","A helicopter with one rotor","Any UAS under four pounds"],"The configuration name reflects the rotor count.","configurations"],
    [5,"Aircraft types","What defines a hexacopter?","A multicopter with six lifting rotors",["A UAS with six batteries","A fixed-wing aircraft with six controls","A helicopter with two rotors"],"Hexa means six.","configurations"],
    [5,"Power systems","Why are batteries common as the primary sUAS power source?","They provide electrical power compactly without fuel storage or combustion hardware",["They eliminate all fire risk","They require no maintenance","They make GPS unnecessary"],"Electric power directly supports controllers, sensors, communications, and motors."],
    [5,"Aircraft systems","Which elements are common to essentially all UAS?","Flight control, propulsion control, a power source, and a control link",["A passenger cabin and transponder","A parachute and radar","Wheels and a combustion engine"],"Every controllable UAS needs these basic functions."],
    [5,"Aircraft types","How does a fixed-wing aircraft primarily generate lift?","Airflow over a wing",["Only downward rotors","A balloon envelope","A ground cable"],"The aircraft normally needs forward airspeed for its wing to produce lift.","configurations"],

    [6,"Aircraft systems","Why is the flight controller called the brain of a UAS?","It interprets pilot commands and sensor inputs, then directs aircraft responses",["It stores landing gear","It physically produces lift","It broadcasts ATIS"],"It coordinates stabilization, navigation, and motor or surface commands.","components"],
    [6,"Aircraft systems","Which sensor measures acceleration and rotation for attitude estimation?","The inertial measurement unit (IMU)",["Landing gear","Camera lens","Propeller guard"],"An IMU commonly contains accelerometers and gyroscopes."],
    [6,"Aircraft systems","What does a magnetometer provide?","Compass or heading information",["Battery capacity","Cloud height","Motor temperature only"],"Magnetic interference can affect heading and navigation."],
    [6,"Aircraft systems","What is component B in the quadcopter diagram?","Electronic speed controller (ESC)",["GPS module","Landing gear","Receiver antenna"],"The ESC regulates its associated electric motor.","components"],
    [6,"Aircraft systems","What is component G in the quadcopter diagram?","Flight controller",["Battery","Propeller","Boom"],"It processes commands and sensor data.","components"],

    [7,"Navigation","Why may GPS fail or perform poorly indoors?","The receiver may not see enough satellites clearly",["Indoor air is too warm","Batteries produce no DC indoors","Controllers cannot transmit indoors"],"Structures attenuate or reflect satellite signals."],
    [7,"Navigation","How does GPS simplify hovering for many multicopters?","Position-hold logic automatically corrects drift",["It locks propellers mechanically","It increases battery capacity","It replaces the controller"],"Without reliable GPS, some modes become less stable or behave differently."],
    [7,"Automation","What is a major Return-to-Home hazard?","The automated route or altitude may intersect obstacles",["It always deletes the home point","It disables all motors","It works only over airports"],"Verify the home point and return altitude; do not assume perfect obstacle sensing."],
    [7,"Power systems","What does mAh describe on a battery?","Electrical capacity",["Motor RPM per volt","Satellite accuracy","Propeller diameter"],"Usable flight time also depends on load and conditions."],
    [7,"Power systems","What does a 2S LiPo designation mean?","Two cells connected in series",["Two spare batteries","Two cells in parallel only","A two-amp limit"],"At about 3.7 nominal volts per cell, 2S is about 7.4 volts."],
    [7,"Power systems","What does a battery's C rating describe?","A charge or discharge rate relative to capacity",["Compass heading","Cell color","Temperature only"],"A 5 Ah pack at 50C corresponds theoretically to 250 A, subject to maker limits."],

    [8,"Aircraft systems","What does an electronic speed controller do?","Controls motor speed and direction and converts battery DC for a brushless motor",["Receives weather data","Tilts the camera mechanically","Measures runway length"],"Multicopters commonly use one ESC per motor."],
    [8,"Aircraft systems","Why are brushless motors widely used?","They are generally reliable, efficient, and quieter than brushed designs",["They need no electricity","They eliminate propellers","They work only with fuel"],"Their electronic commutation requires an ESC."],
    [8,"Flight controls","On a common Mode 2 controller, what does the left stick control?","Throttle and yaw",["Pitch and roll","Camera focus and zoom","Only elevator trim"],"Vertical controls throttle; horizontal controls yaw.","controller"],
    [8,"Flight controls","On a common Mode 2 controller, what does the right stick control?","Pitch and roll",["Throttle and yaw","GPS and Remote ID","Battery and receiver"],"Vertical commands pitch; horizontal commands roll.","controller"],
    [8,"Power systems","Why must LiPo batteries be handled carefully?","Damage or incorrect handling can cause fire or explosion",["They contain no energy","They are harmless when discharged","Impact cannot damage them"],"Follow the manufacturer's charging, inspection, storage, and disposal procedures."],

    [9,"Aircraft systems","Why do multicopter propellers rotate in opposing directions?","To counteract torque and maintain yaw control",["To increase GPS reception","To charge the battery","To create a traffic pattern"],"Same-direction rotation would make control difficult."],
    [9,"Aircraft systems","Why are clockwise and counterclockwise propellers not interchangeable?","Their blade pitch is reversed for the intended rotation direction",["They use different frequencies","Only one contains a motor","One is not a rotor"],"Install each propeller on its matching motor."],
    [9,"Imaging","What does a camera gimbal contribute?","It aims and stabilizes the camera while reducing vibration and tilt",["It authorizes airspace flight","It measures battery capacity","It replaces VLOS"],"A stabilized gimbal can keep imagery level during maneuvers."],
    [9,"Flight controls","What is headless mode?","Directional commands are interpreted from the pilot's perspective rather than aircraft heading",["There is no flight controller","The camera is removed","It is required at night"],"It can simplify orientation but does not replace directional understanding."],
    [9,"Flight controls","What does control trim do?","Makes small adjustments to reduce unwanted drift or bias",["Changes registration","Sets cloud clearance","Calculates damage cost"],"Trim should not mask a mechanical, calibration, or sensor problem."],

    [10,"Flight controls","Roll is rotation about which axis?","The longitudinal nose-to-tail axis",["Vertical","Lateral wingtip-to-wingtip","Runway centerline"],"Ailerons are the primary fixed-wing roll control.","axes"],
    [10,"Flight controls","Pitch is rotation about which axis?","The lateral wingtip-to-wingtip axis",["Longitudinal","Vertical","Magnetic"],"The elevator is the primary fixed-wing pitch control.","axes"],
    [10,"Flight controls","Yaw is rotation about which axis?","The vertical axis",["Longitudinal","Lateral","Camera"],"The rudder is the primary fixed-wing yaw control.","axes"],
    [10,"Flight controls","Which fixed-wing surface primarily commands roll?","Ailerons",["Elevator","Rudder","Landing gear"],"Differential aileron movement changes lift across the wings.","axes"],
    [10,"Flight controls","Which fixed-wing surface primarily commands pitch?","Elevator",["Ailerons","Rudder","Propeller"],"Elevator deflection changes pitching moment about the lateral axis.","axes"],

    [11,"Applications","How can UAS support real-estate work?","By surveying and photographing property from aerial perspectives",["By issuing deeds","By controlling airspace","By replacing all inspections"],"The flight still must follow applicable rules."],
    [11,"Applications","How can UAS assist search and rescue?","By searching terrain with cameras or specialized sensors",["By creating TFRs automatically","By certifying rescuers","By replacing command"],"They can cover difficult areas while limiting human exposure."],
    [11,"Applications","How can utilities use small UAS?","To inspect powerlines, towers, plants, and other assets",["To change regulations","To broadcast ATIS","To eliminate records"],"Remote imaging can reduce some climbing and access risks."],
    [11,"Applications","How can firefighters use UAS?","To monitor fires and gather situational information",["To ignore restrictions","To direct crewed aircraft without coordination","To fly without a remote PIC"],"Emergency operations still require coordination and appropriate authority."],
    [11,"Risk management","What two broad limits constrain possible UAS uses?","Aircraft performance and applicable rules",["Only camera color","Only pilot age","Only runway length"],"A technically possible mission may still be unsafe or unlawful."],

    [12,"Publications","Why should pilots prefer current FAA publications?","Rules, procedures, and operational information change",["Old paper becomes unreadable","Private copies are illegal","FAA sources have no revisions"],"Third-party copies may be incomplete or out of date."],
    [12,"Publications","What is the AIM?","Aeronautical Information Manual",["Aircraft Inspection Mandate","Airspace Identification Map","Automated Incident Message"],"It is a major reference for aviation procedures."],
    [12,"Publications","Which AIM subjects are especially relevant to remote pilots?","Airspace, ATC, procedures, emergencies, safety, and charts",["Only passenger service","Only engine overhaul","Only ticketing"],"Remote pilots share the NAS with crewed aviation."],
    [12,"Publications","What glossary is included in the AIM?","Pilot/Controller Glossary",["Battery glossary","Property-tax glossary","NTSB docket"],"It standardizes terms used by pilots and controllers."],
    [12,"Publications","What is a good first stop for a current FAA publication?","The FAA website",["An old screenshot","An unverified post","A decade-old summary"],"Confirm the publication's revision date."],

    [13,"Airport operations","Starting after takeoff, what sequence names the pattern legs shown?","Upwind, crosswind, downwind, base, final",["Final, base, downwind, crosswind, upwind","Downwind, final, upwind, base, crosswind","Crosswind, base, upwind, final, downwind"],"These are standard traffic-pattern segment names.","pattern"],
    [13,"Airport operations","Which leg is parallel to the runway opposite the landing direction?","Downwind",["Base","Final","Crosswind"],"Aircraft on downwind travel opposite the intended landing direction.","pattern"],
    [13,"Airport operations","Which leg connects downwind to final?","Base",["Upwind","Departure","Crosswind"],"Base is generally at right angles to the runway near its approach end.","pattern"],
    [13,"Airport operations","What is final approach?","Flight along the extended runway centerline toward landing",["Flight opposite landing","The first turn after takeoff","Taxi from parking"],"It begins after the turn from base in the illustration.","pattern"],
    [13,"Airport operations","What warning accompanies the traffic-pattern figure?","It teaches terminology, not a universal pattern-entry method",["It applies only to helicopters","It replaces tower instructions","It depicts a required UAS route"],"Actual procedures depend on the airport, traffic, airspace, and instructions.","pattern"],

    [14,"Publications","Why should an old AIM be treated cautiously?","It may omit later procedural and regulatory changes",["It contains no glossary","It applies to boats","It becomes a NOTAM"],"Check the current edition and changes."],
    [14,"Regulations","What is Part 107's role?","It supplies principal rules for civil small-UAS operations not qualifying for another exception",["It governs only airlines","It is a battery manual","It replaces state law"],"The regulatory path depends on the operation's purpose and circumstances."],
    [14,"Regulations","What generally determines whether a flight is recreational?","The actual purpose and intent of the flight",["Whether it has a camera","Whether the pilot is paid that day","Whether it is a weekend"],"The exception applies only when flown strictly for recreation.","publications","faa-recreation"],
    [14,"Regulations","When uncertain whether a flight fits the recreational exception, what conservative path does the book recommend?","Operate under Part 107",["Ignore both rule sets","Call it recreational later","Use only local law"],"The recreational exception has specific conditions.",null,"faa-recreation"],
    [14,"Publications","What combines regulations and explanatory information in a common pilot reference?","A FAR/AIM publication",["A TAF/METAR report","A battery log","A registration decal"],"Commercial editions often package the FAR and AIM together.","publications"],
    [14,"Regulations","If one rule does not prohibit something, does that alone prove it safe and authorized?","No; other rules, airspace requirements, and risk controls may apply",["Yes, always","Yes, if small","Yes, if no one complains"],"Read the full applicable rule set."],

    [15,"Regulations","What are Part 107's five subparts?","General; Operating Rules; Certification; Operations Over Human Beings; Waivers",["Weather; Airports; Engines; Navigation; Records","Local; State; Federal; Military; Foreign","Registration; Insurance; Taxes; Privacy; Photography"],"The structure helps locate a requirement."],
    [15,"Regulations","What weight defines a small unmanned aircraft at takeoff?","Less than 55 pounds including everything onboard or attached",["55 pounds or less excluding payload","Less than 100 pounds","Exactly 25 kilograms without battery"],"Exactly 55 pounds is not less than 55.",null,"faa-part107"],
    [15,"Language","How does Part 107 define an unmanned aircraft?","An aircraft operated without direct human intervention from within or on it",["Any aircraft with autopilot","Only a military target","Any aircraft below 400 feet"],"The definition focuses on no onboard direct human intervention."],
    [15,"Operating roles","What is a visual observer?","A designated person helping the remote PIC see and avoid traffic and hazards",["The owner","An inspector on every flight","A person watching only camera video"],"The VO supports awareness but does not replace PIC responsibility."],
    [15,"Compliance","What can intentional falsification of Part 107 records cause?","Denial, suspension, revocation, or civil penalty",["Automatic waiver approval","A higher altitude","A new registration"],"FAA compliance records and credentials must not be altered fraudulently."],
    [15,"Compliance","What must covered persons provide during an FAA Part 107 inspection?","Required certificates, records, reports, and access needed to determine compliance",["Only a receipt","Only a pilot photograph","Nothing without a court order"],"The FAA may also inspect the small UAS."],

    [16,"Accident reporting","What is the FAA deadline for a required Part 107 accident report?","Within 10 calendar days",["Within 24 hours always","Within 30 business days","At renewal"],"Use the FAA's designated reporting system.",null,"faa-accident"],
    [16,"Accident reporting","Which injury outcome triggers Part 107 reporting?","Serious injury or loss of consciousness",["Any minor bruise","Only injury to the PIC","Only a fatality"],"Use current FAA definitions.",null,"faa-accident"],
    [16,"Accident reporting","What property-damage threshold triggers FAA reporting?","Damage over $500 to property other than the small UAS",["Any scratch to the UAS","Exactly $100 including the drone","Only damage above $25,000"],"Consider repair or fair-market replacement cost.",null,"faa-accident"],
    [16,"Accident reporting","Does destruction of a $1,000 small UAS alone trigger the property threshold?","No, damage to the small UAS itself is excluded",["Yes, always","Only at night","Only in Class G"],"Other injury or damage could still make it reportable.",null,"faa-accident"],
    [16,"Accident reporting","Does an FAA report replace separately required NTSB notification?","No",["Yes, always","Yes, for public aircraft","Yes, if online"],"FAA and NTSB duties arise under different rules."],
    [16,"Accident reporting","Which example meets the book's serious-injury discussion?","A broken arm",["A clothing smudge","A drained battery","A broken propeller without injury"],"Fracture of most bones is among the cited criteria."],

    [17,"NTSB reporting","When does substantial unmanned-aircraft damage enter the book's NTSB accident definition?","When the aircraft is at least 300 pounds maximum gross takeoff weight",["Whenever a propeller is scratched","Only below 0.55 pounds","At exactly 55 pounds"],"Death or serious injury can independently meet the definition."],
    [17,"NTSB reporting","Which occurrence can require immediate NTSB notification?","An in-flight fire",["A normal low-battery warning","A planned landing","A firmware update"],"Other listed events include certain failures, collisions, and overdue aircraft."],
    [17,"NTSB reporting","Does an expected lost-link response automatically count as a flight-control malfunction?","No; a true uncontrolled fly-away is the concern",["Yes, every return home","Yes, every brief fluctuation","No control event is reportable"],"Behavior and consequences matter."],
    [17,"Certification","May an uncertificated person manipulate controls under Part 107?","Yes, under direct supervision of a qualified pilot who can immediately take control",["Never","Only when alone","Only after an accident report"],"The certificated pilot remains responsible."],
    [17,"Operating roles","Who ensures the operation complies with Part 107?","The remote PIC",["The visual observer alone","The seller","The airport manager"],"The remote PIC is final authority."],
    [17,"Emergencies","What may a remote PIC do during an in-flight emergency?","Deviate as necessary to address the emergency",["Ignore every rule all day","Transfer responsibility to a bystander","Cancel the certificate"],"Submit a written report if the FAA requests it."],
    [17,"Preflight","What must be checked before every flight regarding aircraft condition?","The small UAS must be in a condition for safe operation",["It must be new","It needs retractable gear","It must use fuel"],"Inspect and correct unsafe conditions before launch."],

    [18,"Operating rules","May a small UAS be operated carelessly or recklessly?","No",["Yes in Class G","Yes below 50 feet","Yes with owner permission"],"Part 107 prohibits endangering another's life or property."],
    [18,"Operating rules","When may objects be dropped from a small UAS?","Only when the drop does not create an undue hazard",["Whenever light","Only over a road","Never under any circumstance"],"The created hazard is the concern."],
    [18,"Moving vehicles","Can a pilot operate a small UAS from a moving aircraft?","No",["Yes below 400 feet","Yes over water","Yes with a VO"],"The moving-vehicle exception does not extend to aircraft."],
    [18,"Moving vehicles","When can operation from a moving land or water vehicle fit the basic rule?","In a sparsely populated area and not carrying another's property for compensation or hire",["On a crowded street","Whenever the driver is PIC","Only at twilight"],"A waiver cannot permit the excluded property carriage."],
    [18,"Human factors","What is the minimum bottle-to-throttle interval discussed?","8 hours",["2 hours","4 hours","24 hours"],"A person also must not be impaired or at or above the alcohol limit."],
    [18,"Night operations","How visible must anti-collision lighting be at night?","At least 3 statute miles",["500 feet","1 statute mile","10 nautical miles"],"The pilot must also meet current night-training requirements.",null,"faa-part107"],
    [18,"Operating rules","What must VLOS allow the crew to determine?","Location, attitude, altitude, direction, and nearby hazards",["Only battery serial number","Only camera exposure","Only home coordinates"],"The crew must also watch for traffic and risks."],
    [18,"Operating rules","How many simultaneous operations may one person serve as PIC or VO for?","One",["Two","Four","Any number below 100 feet"],"The restriction applies at any given time."],

    [19,"Right of way","To whom must a small UAS yield?","All other aircraft and airborne vehicles",["Only airliners","Only helicopters","No one below 400 feet"],"Remain well clear and never create a collision hazard."],
    [19,"Operations over people","Is ordinary flight over people automatically allowed?","No; it must fit an authorized category or other provision",["Yes below 50 feet","Yes if brief","Yes with insurance"],"Categories 1–4 impose different conditions.",null,"faa-people"],
    [19,"Airspace","Which airspace generally requires prior ATC authorization?","Class B, C, D, and surface Class E",["All Class G","Only warning areas","Only above 18,000 feet"],"Use LAANC where available or the applicable manual process.",null,"faa-laanc"],
    [19,"Airport operations","What must a pilot avoid near any airport, heliport, or seaplane base?","Interfering with traffic patterns and operations",["Listening to weather","Using a checklist","Maintaining VLOS"],"Heliports may be less obvious than large airports."],
    [19,"Special use airspace","What is the practical meaning of prohibited airspace?","Entry is not allowed without controlling-authority permission",["Always allowed below 400 feet","Only a weather advisory","Exists only at night"],"Prohibited areas protect sensitive locations."],
    [19,"Special use airspace","Can restricted airspace be inactive at published times?","Yes",["No, never","Only under 0.55 pounds","Only without ATIS"],"Check charts and current status."],
    [19,"NOTAMs","What events can create flight restrictions by NOTAM?","Disasters, presidential movement, space operations, airshows, and major sports",["Only battery charging","Only property sales","Only address changes"],"Check current NOTAMs and TFRs before every operation."],

    [20,"Preflight","What environments must the remote PIC evaluate?","Both surface and air operating environments",["Only the launch pad","Only an online map","Only distant weather"],"Assess risks to people and property."],
    [20,"Preflight","Which items belong in a preflight assessment?","Weather, airspace, restrictions, people, property, and ground hazards",["Only battery color","Only camera settings","Only customer schedule"],"Powerlines, bystanders, vehicles, and restrictions are examples."],
    [20,"Crew briefing","What must participating crewmembers know?","Conditions, emergency procedures, roles, responsibilities, and hazards",["Only aircraft price","Only PIC address","Nothing until launch"],"A shared briefing reduces confusion."],
    [20,"Control link","What must be confirmed about the control link?","It works adequately for the planned operation",["It uses a specific brand","It is visible to ATC","It broadcasts music"],"Consider range, interference, antennas, and lost-link behavior."],
    [20,"Operating limits","What is the ordinary maximum groundspeed?","87 knots or 100 mph",["55 knots","120 knots","No limit"],"Groundspeed is the stated quantity."],
    [20,"Operating limits","What is the ordinary altitude limit away from structures?","400 feet AGL",["400 feet MSL","500 feet AGL","1,200 feet AGL"],"Airspace ceilings and restrictions can be lower.",null,"faa-part107"],
    [20,"Operating limits","What is the basic structure exception?","Within 400 feet of the structure and no more than 400 feet above its top",["Any height above a structure","Add 1,200 feet","Only indoors"],"Other authorization requirements still apply."],
    [20,"Operating limits","What visibility and cloud clearance normally apply?","3 SM visibility; 500 feet below and 2,000 feet horizontally from clouds",["1 SM and clear of clouds","5 SM and 1,000 feet above","No minimum below 400 feet"],"Visibility is evaluated from the control station."],

    [21,"Certification","What is the minimum age for a Part 107 certificate?","16",["14","18","21"],"Applicants also meet language, knowledge, and fitness requirements.",null,"faa-pilot"],
    [21,"Certification","What English ability is generally required?","Ability to read, speak, write, and understand English",["Reading only","No requirement","Abbreviations only"],"The FAA rules address limited exceptions."],
    [21,"Human factors","What health standard applies to eligibility?","No known condition that would interfere with safe operation",["A first-class medical","Perfect uncorrected eyesight","No standard"],"No routine medical certificate is required, but safe fitness is."],
    [21,"Certification","How does a first-time non-Part-61 applicant show knowledge?","Pass the initial Unmanned Aircraft General test",["Take a driving test","Submit photos","Fly solo 40 hours"],"The result supports the application.",null,"faa-pilot"],
    [21,"Certification","What online system is commonly used to apply?","IACRA",["LAANC","ATIS","METAR"],"It means Integrated Airman Certification and Rating Application."],
    [21,"Certification","What identifier does IACRA issue?","FAA Tracking Number (FTN)",["Tailwheel number","Visibility code","NOTAM keyword"],"It links testing and certification records."],
    [21,"Certification","How long can a temporary certificate remain valid under the cited rule?","Up to 120 days",["10 days","30 days","24 months"],"It can end sooner when a permanent certificate is issued or the application is denied."],

    [22,"Certification","What passing score is stated for the UAG test?","70 percent",["60 percent","80 percent","100 percent"],"Verify current requirements with the FAA."],
    [22,"Certification","After failing the UAG test, what waiting period is cited?","14 calendar days",["24 hours","30 days","One year"],"Use the interval to review weak areas."],
    [22,"Certification","What can knowledge-test cheating cause?","A one-year bar and possible certificate suspension or revocation",["Same-day retest","Only a warning","A higher passing score"],"Unauthorized copying, aid, and impersonation are prohibited."],
    [22,"Knowledge areas","Which subjects belong to remote-pilot training?","Rules, airspace, weather, loading, emergencies, CRM, communications, performance, ADM, airports, maintenance, preflight, and night",["Only photography","Only purchasing","Only property taxes"],"Certification requires broad aeronautical knowledge."],
    [22,"Certification","Within how long must an address change be reported?","30 days",["10 days","90 days","At recurrent training"],"Use the current FAA process."],
    [22,"Certification","What follows voluntary certificate surrender?","The person must satisfy applicable requirements again to regain it",["It returns after 30 days","Nothing changes","It becomes a waiver"],"Surrender is cancellation, not storage."],
    [22,"Operations over people","Why are operations-over-people categories risk-based?","Different aircraft designs and weights create different injury risks",["Every aircraft creates identical risk","Only camera type matters","They apply only at airports"],"Rules connect eligibility and limitations to expected harm."],

    [23,"Operations over people","What is the maximum Category 1 takeoff weight?","Less than 0.55 pounds including attachments",["55 pounds","Exactly 0.55 excluding propellers","Less than 5 pounds"],"It must remain below the limit throughout.",null,"faa-people"],
    [23,"Operations over people","What exposed-part restriction applies to Category 1?","No exposed rotating parts able to lacerate skin",["No camera","No battery","No landing gear"],"A protected design may be needed."],
    [23,"Remote ID","What additional requirement applies to Category 1 over-people operations?","Compliance with applicable Remote ID requirements",["A crewed transponder","A first-class medical","An airport gate"],"Check current Part 89 guidance.",null,"faa-register"],
    [23,"Operations over people","Which categories rely on FAA-accepted means and declarations of compliance?","Categories 2 and 3",["Category 1 only","Category 4 only","No category"],"Applicants substantiate injury-risk and design requirements."],
    [23,"Operations over people","What distinguishes Category 4 aircraft?","An airworthiness certificate and associated limitations",["Under 0.55 pounds","No maintenance records","Ignoring the flight manual"],"Category 4 has formal maintenance and records."],
    [23,"Moving vehicles","For Categories 1–3, what are two basic pathways over people in moving vehicles?","A restricted-access site with notice, or no sustained flight over vehicles",["Indefinite highway flight","Driver approval only","Below 400 feet only"],"Check current category conditions.",null,"faa-people"],
    [23,"Operations over people","May an aircraft switch inadvertently between category configurations airborne?","No",["Yes with one switch","Yes below 50 feet","Yes with GPS"],"Variable configurations must prevent inadvertent mode changes."],

    [24,"Compliance","What may establish a means of compliance for Categories 2 and 3?","Test, analysis, or inspection",["A social review","Pilot opinion","Property-owner waiver"],"The submission shows the design meets performance requirements."],
    [24,"Compliance","Can the FAA rescind an accepted means of compliance?","Yes, if it no longer meets requirements",["No, never","Only the maker can","Only after ten years"],"The FAA uses the prescribed public process."],
    [24,"Compliance","What follows acceptance of a means of compliance?","Submit a declaration of compliance for FAA acceptance",["Automatic Category 4","A medical certificate","No further record"],"The declaration must be retained and available."],
    [24,"Waivers","What is a Part 107 waiver?","FAA approval for a described operation outside specified limitations",["Exemption from all law","A property permit","Registration"],"Waivers are case-specific and require a safety case.",null,"faa-waivers"],
    [24,"Waivers","Where are waiver applications submitted?","FAA DroneZone",["IACRA only","Tax office","ATIS"],"Follow current instructions and answer FAA requests.",null,"faa-waivers"],
    [24,"Emergency operations","What does the Special Governmental Interest process support?","Expedited consideration for qualifying emergency or disaster operations",["Routine recreation","Automatic pilot certification","Permanent prohibited-area access"],"Examples include firefighting, rescue, law enforcement, restoration, assessment, and crucial media."],
    [24,"Airspace","What data can LAANC evaluate?","Facility maps, airspace, airports, special-use areas, TFRs, and NOTAMs",["Aircraft color","Quiz score","Only property boundaries"],"Approved suppliers exchange request data with FAA systems.","laanc","faa-laanc"],
    [24,"Airspace","Does LAANC eliminate other preflight checks?","No",["Yes, completely","Only for recreation","Only at night"],"Authorization is limited by location, time, altitude, and conditions.","laanc","faa-laanc"],

    [25,"Local rules","What does ignorantia juris neminem excusat mean?","Ignorance of the law is not an excuse",["Local rules never apply","Federal rules can be ignored","Every flight needs a court order"],"Research applicable federal, state, local, and site requirements."],
    [25,"Local rules","Why can drone rules vary by location?","Different authorities regulate different matters within their powers",["FAA rules change each street","Weight has no definition","Only weather matters"],"Airspace, land use, privacy, trespass, and police powers differ."],
    [25,"Federalism","What is the Supremacy Clause's general effect?","Valid federal law can preempt conflicting state or local law",["Local law always wins","It applies only to weather","It grants pilots all airspace"],"Preemption is complex; a flight should not be treated as a courtroom test."],
    [25,"Local rules","What is the practical response to a questionable local restriction?","Comply in the moment and seek authoritative guidance through proper channels",["Argue during the flight","Ignore it automatically","Use a social poll"],"Operational confrontation is unsafe and legal challenges are costly."],
    [25,"Professionalism","Why should pilots represent the industry responsibly?","Good conduct builds trust and reduces pressure for restrictive responses",["It removes all rules","It guarantees waivers","It makes privacy irrelevant"],"Professional behavior matters even when conduct is not expressly prohibited."],

    [26,"Privacy","Does the FAA principally regulate personal privacy disputes?","No; other federal, state, and local law generally addresses privacy",["Yes, every privacy claim","Only abroad","Only above 500 feet"],"Research other applicable law."],
    [26,"Privacy","What simple privacy principle does the chapter emphasize?","Use good judgment and be a good neighbor",["Record everything","Assume owners have no rights","Publish automatically"],"Avoid harassment and intrusive conduct."],
    [26,"Publications","How often is the Chart Supplement revised?","Every 56 days",["Every 7 days","Every five years","Only on closure"],"Use the current regional volume."],
    [26,"Publications","What does the Chart Supplement add beyond a chart symbol?","Detailed airport, runway, service, communication, and procedural information",["Only ownership","Only battery guidance","Only privacy law"],"It also contains notices, contacts, parachute areas, and diagrams."],
    [26,"Publications","What is the Aeronautical Chart Bulletin for?","Reporting chart-relevant obstacles and hazards found since printing",["Publishing test scores","Listing drones","Approving waivers"],"Information can be included in the next chart edition."],

    [27,"Publications","Are Advisory Circulars generally regulations?","No; they generally explain rules or compliance methods",["Yes, every AC is CFR","They are weather observations","They are deeds"],"Their legal status differs from regulatory text."],
    [27,"Publications","How are many Advisory Circulars numbered?","To correspond with the related regulatory subject",["By aircraft serial","By airport elevation","Randomly"],"Number series align with subject areas."],
    [27,"Publications","What can a sectional-chart QR code lead to?","Chart guides, supplements, NOTAMs/TFRs, alerts, and updates",["Only an application","A camera feed","An automatic waiver"],"QR links help reach current information."],
    [27,"NOTAMs","Why check NOTAMs close to departure?","Restrictions and hazards can appear with little warning",["They never change","They concern airlines only","They are indoor only"],"TFRs can affect a familiar site."],
    [27,"Currency","How should a pilot stay current?","Monitor official FAA changes and reputable aviation safety information",["Use only the first textbook edition","Ignore proposals","Use only comments"],"The FAA is authoritative for its rules and policies."],

    [28,"NOTAMs","What does the keyword RWY identify?","A runway-related condition",["A frequency change","A fuel issue","An obstacle outage"],"A runway closure begins with RWY.","notams"],
    [28,"NOTAMs","What does the keyword TWY identify?","A taxiway-related condition",["A runway closure","A navigation outage","An airshow"],"The example reports taxiway lights out.","notams"],
    [28,"NOTAMs","In a NOTAM, what does OTS mean?","Out of service",["On the surface","Over the station","Open to sUAS"],"It can describe unavailable lights, beacons, aids, or communications.","notams"],
    [28,"Altitude","How do MSL and AGL differ in an obstacle NOTAM?","MSL is elevation above sea level; AGL is height above local ground",["They are identical","MSL is distance","AGL is a frequency"],"An obstacle may be reported with both values.","notams"],
    [28,"NOTAMs","What does the keyword COM identify?","A communications-related condition",["A runway condition","An apron closure","An obstacle"],"The example reports an ATIS frequency out of service.","notams"],

    [29,"Charts","About how many nautical miles per inch does a sectional chart depict?","About 8 nautical miles per inch",["About 1 nautical mile per inch","About 4 nautical miles per inch","About 60 nautical miles per inch"],"That scale keeps sectionals large enough for landmark navigation without being unmanageable."],
    [29,"Charts","How often are sectional charts normally reissued?","Every six months",["Every 30 days","Every 56 days","Every year"],"Treat an older chart with caution and check current NOTAMs to fill any gap."],
    [29,"Charts","What kind of chart uses a larger scale for the busiest airports with Class B airspace?","A terminal area chart",["A sectional chart","A world aeronautical chart","An enroute low-altitude chart"],"The larger scale keeps detail readable in congested airspace."],
    [29,"Publications","How often is the Chart Supplement issued?","Every 56 days",["Every 6 months","Every 24 hours","Once a year"],"It carries details, such as part-time tower hours, that don't appear on any other aeronautical publication."],
    [29,"Regulations","Does Part 107 require a remote pilot to carry a current aeronautical chart in flight?","No; carrying a chart is not required under Parts 101 or 107",["Yes, an updated sectional must be onboard","Yes, but only a terminal area chart qualifies","Yes, unless flying under a waiver"],"Even so, pilots still need current information before flying safely and legally."],

    [30,"Navigation","What are lines of latitude also called?","Parallels",["Meridians","Isogonic lines","Agonic lines"],"They run east-west and measure position north or south of the Equator.","meridiansDiagram"],
    [30,"Navigation","What are lines of longitude also called?","Meridians",["Parallels","Isobars","Sectionals"],"They converge at the poles and measure position east or west of the prime meridian."],
    [30,"Navigation","Where does the prime meridian (0° longitude) pass through?","Greenwich, England",["Washington, D.C.","The Equator at 0° latitude","Ellensburg, Washington"],"It's the reference line for measuring longitude east and west."],
    [30,"Navigation","About how many nautical miles equal one minute of latitude?","One nautical mile",["One statute mile","Ten nautical miles","Sixty nautical miles"],"That's why latitude scales double as a distance ruler on aeronautical charts."],
    [30,"Time","What reference time standard uses Greenwich as its 0° line and is shown with a 'Z' suffix?","Coordinated Universal Time (UTC), or Zulu time",["Local standard time","Daylight saving time","Mountain time"],"UTC gives pilots a single, consistent time reference regardless of location."],

    [31,"Navigation","About how many feet are in one nautical mile?","About 6,076 feet",["5,280 feet","6,000 feet exactly","8,000 feet"],"A nautical mile is somewhat longer than a statute mile (5,280 feet)."],
    [31,"Navigation","Which unit does the FAA use for most aeronautical distance measurements, aside from visibility?","Nautical miles",["Statute miles","Kilometers","Fathoms"],"Airspeed is also normally expressed in knots, or nautical miles per hour."],
    [31,"Navigation","What causes magnetic variation?","The difference in position between the magnetic north pole and the true (geographic) north pole",["Differences between local time zones","Errors in GPS satellite signals","Seasonal changes in wind direction"],"Compasses point toward magnetic north, not true north, so pilots must correct for the difference."],
    [31,"Charts","On a sectional chart, what do isogonic lines connect?","Points with identical magnetic variation",["Points with identical elevation","Airports with the same radio frequency","Points along the same meridian"],"The isogonic line with zero variation is called the agonic line."],
    [31,"Time","What must remote pilots often convert local flight-planning times to before checking many weather and NOTAM products?","Coordinated Universal Time (UTC, or Zulu time)",["Daylight saving time only","The time zone of the manufacturer","Solar time"],"Weather briefings and NOTAMs are commonly issued in Zulu time."],

    [32,"Navigation","What is the agonic line?","The line where magnetic variation is zero, so true and magnetic north align",["The line of zero latitude","The boundary of Class A airspace","A line connecting all VOR stations"],"East and west of the agonic line, variation shifts in opposite directions across the continental U.S."],
    [32,"Navigation","If magnetic variation is 14° east, what must a pilot do to convert a true course to a magnetic course?","Subtract 14°",["Add 14°","Multiply by 14","Ignore it below 10,000 feet"],"A common memory aid is that easterly variation is subtracted from a true course."],
    [32,"Navigation","If magnetic variation is 10° west, what must a pilot do to convert a true course to a magnetic course?","Add 10°",["Subtract 10°","Divide by 10","Add 100°"],"Westerly variation is added to a true course to get the magnetic course."],
    [32,"Navigation","What does a wind correction angle compensate for?","Wind drift, so the aircraft's track over the ground matches the planned course",["Errors in magnetic compass calibration","Differences between MSL and AGL altitude","Battery voltage sag in cold weather"],"Determining the correction involves wind direction, wind velocity, true airspeed, and true course.","windCorrection"],
    [32,"Operations","Why is a computed wind correction angle usually less critical for an ordinary VLOS sUAS flight than for a long-range crewed flight?","The remote pilot can correct the flight path visually within line of sight rather than through navigation calculations",["Wind never affects small UAS","VLOS flights are always conducted indoors","Small UAS are immune to crosswinds"],"Beyond-VLOS operations are more likely to rely on the same sophisticated navigation systems and computed wind corrections crewed aircraft use."],

    [33,"Navigation","What is the difference between groundspeed and airspeed?","Groundspeed is speed over the ground; airspeed is speed through the air mass, which wind affects differently",["They are always identical","Groundspeed only applies to helicopters","Airspeed is measured only in MPH"],"A headwind reduces groundspeed while a tailwind increases it, even though airspeed stays the same."],
    [33,"Charts","On a sectional chart, what does the bold, larger number next to an obstruction symbol usually represent?","The obstruction's height above mean sea level",["Its height above ground level only","Its FCC registration number","Its distance from the nearest airport"],"The smaller number, often in parentheses, is typically the height above ground level."],
    [33,"Charts","What does a group obstruction symbol (two symbols close together) on a sectional chart indicate?","There are two or more obstructions close together in that area",["A single very tall tower","A temporary flight restriction","A wildlife refuge boundary"],"Check the chart legend for the exact meaning of grouped obstruction symbols."],
    [33,"Charts","Why should remote pilots pay attention to natural terrain elevation as well as charted obstructions?","Terrain elevation changes affect the true altitude needed to maintain safe clearance",["Terrain never changes so it can be ignored","Only man-made obstacles matter for sUAS","Terrain is not shown on sectional charts"],"The measured altitude block on a sectional shows the highest terrain and obstruction height within a quadrangle, plus a safety margin."],
    [33,"Charts","What resource can pilots check for current radio frequencies and airspace designations for an area?","The aeronautical chart and its legend",["Only the aircraft flight manual","The pilot's logbook","A generic road atlas"],"Bookmarking a chart legend and reviewing it before a written test is time well spent."],

    [34,"Airspace","What must remote pilots be aware of at all times regarding the National Airspace System?","Their position in three dimensions relative to controlled and uncontrolled airspace",["An assigned squawk code","A filed instrument flight plan","A second remote pilot certificate"],"Airspace regulations exist to keep operations separated safely."],
    [34,"Airspace","What is the key practical difference between controlled and uncontrolled airspace for a remote pilot?","Controlled airspace may require specific ATC authorization before sUAS operations; uncontrolled airspace generally does not",["Controlled airspace has no weather reporting","Uncontrolled airspace is always over water","There is no difference for sUAS operations"],"Class G airspace is the primary example of uncontrolled airspace in the U.S."],
    [34,"Language","How many letters typically make up the international identifier for a U.S. NAVAID or airport?","Four",["Two","Three","Six"],"The FAA drops the leading 'K' for most airports in the lower 48 states when using the shorter three-letter version."],
    [34,"Language","What does the FAA's three-letter domestic airport identifier usually omit compared with its four-letter international version?","The leading 'K' prefix used for most locations in the lower 48 states",["The airport's city name","Its runway numbers","Its magnetic variation"],"Hawaii and Alaska instead use a leading 'P', and Puerto Rico uses a leading 'T'."],
    [34,"Airspace","Who is responsible for detecting airspace violations in controlled airspace?","Air traffic control",["Only the National Weather Service","Local police departments","Airport ground crews"],"That's one reason controlled-airspace regulations exist — to keep ATC aware of who is operating nearby."],

    [35,"Airspace","From what altitude does Class A airspace begin over the continental United States?","18,000 feet MSL",["10,000 feet MSL","14,500 feet MSL","Flight Level 600"],"Class A airspace runs from 18,000 feet MSL up to Flight Level 600."],
    [35,"Airspace","Are ordinary small UAS operations normally permitted in Class A airspace?","No, standard sUAS operations are not permitted in Class A airspace",["Yes, without any authorization","Yes, but only above 20,000 feet","Only large-scale UAS are ever excluded"],"Even large UAS need specific authorization to fly that high."],
    [35,"Charts","How is the floor of Class B airspace typically shown on a sectional chart?","As a fraction near each segment, with the bottom number giving the floor in hundreds of feet MSL",["As a solid red line","It is never shown on charts","As a percentage of ground elevation"],"A floor value of 100, for example, means 10,000 feet MSL.","airspaceClasses"],
    [35,"Airspace","What must a remote pilot obtain before operating within Class B airspace?","Specific ATC authorization",["Nothing; Class B is uncontrolled","A statement from the airport manager only","Approval from the National Weather Service"],"Class B surrounds the nation's busiest airports."],
    [35,"Airspace","Are student pilots of crewed aircraft normally free to operate at every Class B airport?","No; they, and often sUAS as well, are commonly restricted from some of the busiest Class B airports",["Yes, without restriction","Only at night","Only with a co-pilot"],"Double-check restrictions before flying near a super-busy Class B airport."],

    [36,"Airports","What kind of airports appear on the FAA's list of Class B primary airports?","Major international airports in large U.S. cities, such as Los Angeles, Chicago, and Atlanta",["Only small private grass strips","Only military-only airfields","Airports located exclusively in Alaska"],"Nearly every major U.S. metropolitan area has a Class B primary airport."],
    [36,"Airspace","What special restriction applies to the Washington, D.C., area regardless of airspace class?","It is a 'No Drone Zone' with additional flight prohibitions",["It has no restrictions at all","Only manned aircraft may be restricted there","It only applies during business hours"],"Remote pilots should check current FAA guidance on the no-drone-zone before flying anywhere near D.C."],
    [36,"Charts","How is the horizontal boundary of Class C airspace typically shown on a sectional chart?","With solid magenta circles",["With dashed blue circles","With solid black squares","With a green shaded oval"],"sUAS operations still need authorization to enter Class C airspace."],
    [36,"Airspace","Do all Class C airspace areas operate 24 hours a day?","No; many operate only part-time",["Yes, always","Only on weekends","Only above 10,000 feet"],"Check the sectional chart notation or the Chart Supplement for actual operating hours."],
    [36,"Airspace","What kind of airports commonly sit beneath the outer ring of a Class C airspace area?","Smaller satellite airports located under the shelf of the surrounding Class C airspace",["Only Class A primary airports","Airports with no runways","Airports outside the United States"],"Operating near a satellite airport still places a pilot within Class C airspace considerations."],

    [37,"Airspace","What typically happens to Class C airspace when it is not in effect, outside its operating hours?","It reverts to another airspace class described on the chart or in the Chart Supplement, often Class E or G",["It becomes Class A automatically","It disappears with no other airspace in its place","It becomes a permanent restricted area"],"You must check the Chart Supplement to know exactly what airspace is left behind."],
    [37,"Airspace","What normally triggers the existence of Class D airspace at an airport?","An operating control tower",["A NAVAID location","Proximity to a national park","A minimum runway length"],"When a part-time tower closes for the day, its Class D airspace requirement usually goes away too."],
    [37,"Charts","How is the horizontal boundary of Class D airspace typically shown on a sectional chart?","With a blue dashed line",["With a solid magenta circle","With a green dotted line","With black diagonal hatching"],"The airport symbol is also shown in blue when a tower is present."],
    [37,"Airspace","What is the standard vertical extent of Class D airspace above the airport elevation?","Up to 2,500 feet above the airport, or to the base of overlying airspace",["Up to 18,000 feet MSL","Up to 1,200 feet AGL only","There is no vertical limit"],"Actual shapes vary with cutouts, shelves, and extensions for instrument traffic."],
    [37,"Airspace","Where does Class E airspace typically extend upward to?","The floor of the next overlying controlled airspace, such as Class A, B, or C",["Always exactly 700 feet AGL","Always exactly 10,000 feet MSL","It has no upper limit"],"Its floor, by contrast, can be at the surface, 700 feet AGL, 1,200 feet AGL, or 14,500 feet MSL depending on location."],

    [38,"Charts","On a Class C sectional excerpt like Spokane's, what typically surrounds both a civilian airport and a nearby military airfield?","A single shared area of Class C airspace",["A single shared Class B area","A prohibited area","A military operations area only"],"Multiple satellite airports can sit beneath the outer ring of that Class C airspace."],
    [38,"Charts","What does the fraction shown within a segment of Class C airspace on a sectional chart represent?","The ceiling over the floor, both in hundreds of feet MSL",["Radio frequency over squawk code","Runway length over width","Latitude over longitude"],"For example, a fraction of 40 over 13 means the segment runs from 1,300 feet MSL up to 4,000 feet MSL."],
    [38,"Airspace","At a Class C airport located right at a naval air station, what is the floor of the Class C airspace directly over the airport surface itself?","The surface",["18,000 feet MSL","10,000 feet MSL","700 feet AGL"],"The fraction for that segment effectively runs down to the ground at the airport."],
    [38,"Airspace","Why should a remote pilot pay attention to satellite airports located beneath a Class C outer ring?","Operating near them still places the pilot beneath or within Class C airspace, which carries its own considerations",["Satellite airports are always outside all controlled airspace","Satellite airports cancel Class C requirements","Satellite airports only matter for balloon operations"],"The airspace class governs the airspace regardless of which airport is nearest."],
    [38,"Charts","What visual feature distinguishes a Class C boundary from a Class D boundary on the same sectional chart?","Class C is drawn with solid magenta circles, while Class D is drawn with a blue dashed line",["Both use identical solid black lines","Class C is always red, Class D is always green","Neither class is shown on sectional charts"],"Matching line style to airspace class is a core sectional-chart-reading skill."],

    [39,"Airspace","What is a 'cutout' in Class D airspace used for?","Excluding a non-tower airport from the surrounding Class D area",["Marking the location of a NAVAID","Showing a temporary flight restriction","Indicating a wildlife refuge"],"A cutout carves a separate section out of the surrounding Class D airspace.","classDCutout"],
    [39,"Airspace","What is a 'shelf' or extension used for in Class D or Class E airspace?","Allowing pilots to fly into and out of airports located beneath the edges of the airspace",["Blocking all aircraft from entering the area","Marking Restricted Area boundaries","Indicating a runway closure"],"Shorter extensions of 2 NM or less still require tower permission; longer ones don't carry the same communication requirement."],
    [39,"Airspace","Where does most Class G, or uncontrolled, airspace exist relative to the ground?","Beneath the floors of controlled airspace, often below 700 or 1,200 feet AGL",["Only above 18,000 feet MSL","Only over international waters","Only inside Restricted Areas"],"Class G exists wherever another airspace class does not."],
    [39,"Airspace","Can the FAA establish a temporary control tower inside airspace that was previously Class G?","Yes, for special events such as fly-ins or major sporting events",["No, control towers are always permanent","No, temporary towers are illegal","Only inside Class A airspace"],"Temporary towers won't appear on sectional charts, but they are announced by NOTAM."],
    [39,"Navigation","What is the main advantage of newer Tango (T) airways compared with Victor airways?","They are navigated using GPS and help route traffic around congested or special-use airspace",["They exist only above 18,000 feet MSL","They eliminate the need for any airspace authorization","They replace all Class E airspace"],"Both Victor and Tango routes are shown as blue lines on sectional charts, but Tango routes are GPS-based."],

    [40,"Airspace","What does TRSA stand for, and how is it shown on a sectional chart?","Terminal Radar Service Area, shown with a solid black circle",["Temporary Restricted Service Area, shown in red","Tower Radio Service Area, shown with a dashed line","Traffic Reporting Sector Area, shown in green"],"It functions like a voluntary version of Class C airspace."],
    [40,"Airspace","What is the most restrictive type of special use airspace?","A Prohibited Area",["A Warning Area","An Alert Area","A Military Operations Area"],"There is essentially no way to get permission to fly a sUAS in a Prohibited Area, such as the one over the White House."],
    [40,"Airspace","Who typically designates and controls a Restricted Area?","The military, often around firing ranges or other hazardous activity",["Local city governments","The National Park Service","Commercial airlines"],"A table on the sectional chart lists operating hours and altitudes, but pilots should still confirm current status with FSS or the controlling agency."],
    [40,"Regulations","What is a Temporary Flight Restriction (TFR) typically issued for?","Added security around events such as sporting events or gatherings of high-profile officials",["Routine daily airport operations","Permanent airspace redesign","Weather reporting stations"],"TFRs are published by NOTAM, and remote PICs are just as responsible as crewed pilots for checking them."],
    [40,"Airspace","What is a National Security Area (NSA)?","A permanent area where pilots are asked, but not required, to voluntarily avoid flying",["A mandatory no-fly zone with criminal penalties","A temporary weather advisory","A GPS-only navigation corridor"],"An NSA can be converted to prohibited airspace by NOTAM if needed."],

    [41,"Airspace","Where are Warning Areas typically located?","Offshore, in international waters",["Only over national parks","Only within Class B airspace","Only inside city limits"],"They carry hazards similar to Restricted Areas, but specific permission is not required — pilots should just stay alert."],
    [41,"Airspace","What does an Alert Area indicate?","A high volume of pilot training or unusual aerial activity",["A prohibited government facility","A permanent flight ban","A wildlife nesting ground"],"No clearance is required for an Alert Area, but extra vigilance is expected."],
    [41,"Charts","How is a Military Operations Area (MOA) typically shown on a sectional chart?","With magenta hatching",["With a solid black circle","With blue dashed lines","With a green shaded triangle"],"Military aircraft can operate in a MOA at high speed without complying with the same regulations as other traffic."],
    [41,"Airspace","Does a remote pilot need specific permission to fly in an active MOA?","No, but extreme caution is strongly advised",["Yes, always from the FAA Administrator","Yes, from the nearest airline","No permission or caution is needed"],"Military pilots inside a MOA are not necessarily looking out for small UAS."],
    [41,"Airspace","What distinguishes a four-digit Military Training Route (MTR) from a three-digit one?","Four-digit MTRs are flown at or below 1,500 feet AGL, closer to typical sUAS altitudes",["Four-digit MTRs are always offshore","Three-digit MTRs never involve jets","Four-digit MTRs only exist at night"],"That makes four-digit MTRs the ones of greatest concern for remote pilots."],

    [42,"Airspace","What is an Air Defense Identification Zone (ADIZ)?","Airspace along U.S. coasts where inbound aircraft must be identified, or risk interception",["A zone reserved exclusively for drone racing","An area with no radio requirements at all","A temporary zone created only during air shows"],"Regulations don't spell out specific sUAS ADIZ requirements, but pilots should avoid or coordinate with ATC near them."],
    [42,"Airspace","What is the general UAS flight restriction around Washington, D.C.?","UAS flight is prohibited within the District of Columbia and within a 30 nautical mile radius of Reagan Washington National Airport",["UAS may fly freely above 400 feet","Only nighttime UAS flights are restricted","The restriction applies only on federal holidays"],"This is one of the most well-known and strictly enforced no-drone-zones in the country."],
    [42,"Charts","What does a dotted-line boundary on a sectional chart near a place like a national park often indicate?","A wildlife refuge area",["A restricted military area","A Class D surface area","An agricultural spraying zone"],"Pilots are asked, but not required, to stay at least 2,000 feet above the terrain there to reduce noise disturbance to wildlife."],
    [42,"Regulations","Are UAS generally permitted to fly within National Parks?","No, UAS are not permitted to fly in National Parks",["Yes, without restriction","Only with a park ranger riding along","Only below 100 feet"],"Additional local or regional park restrictions may also apply."],
    [42,"Regulations","What kind of penalty can result from harassing wildlife with a UAS in a refuge area?","Monetary fines and/or imprisonment",["A warning letter only, with no further consequence","Automatic loss of aircraft registration only","No penalty as long as it is unintentional"],"Harassment can be penalized regardless of whether it was intentional."]
  ];

  const pageCounters = {};
  const facts = rows.map((row) => {
    const [page, topic, question, answer, distractors, explanation, figureKey, verificationSource] = row;
    pageCounters[page] = (pageCounters[page] || 0) + 1;
    const number = String(page).padStart(2, "0");
    const figure = figureKey ? figures[figureKey] : null;
    return {
      id: `p${number}-${String(pageCounters[page]).padStart(2, "0")}`,
      book: "completeRemotePilot", chapter: page <= 10 ? "1" : page <= 28 ? "2" : "3", page: number,
      topic, question, answer, distractors, explanation, source: `book-${number}`,
      verificationSource: verificationSource || null,
      image: figure?.[0], imageAlt: figure?.[1]
    };
  });

  const flashcards = facts.map((fact) => ({
    ...fact, id: `c-${fact.id}`, distractors: undefined
  }));
  const questions = facts.map((fact, index) => {
    const initial = [fact.answer, ...fact.distractors];
    const rotation = index % 4;
    const options = [...initial.slice(rotation), ...initial.slice(0, rotation)];
    return {
      id: `q-${fact.id}`, book: fact.book, chapter: fact.chapter, page: fact.page,
      topic: fact.topic, question: fact.question, options, answer: options.indexOf(fact.answer),
      explanation: fact.explanation, source: fact.source, verificationSource: fact.verificationSource,
      image: fact.image, imageAlt: fact.imageAlt
    };
  });

  window.STUDY_DATA = {
    meta: {
      title: "FAA Remote Pilot — source pages 01–42", version: 3,
      reviewed: "2026-09-24", pageCount: 42,
      note: "Every source page has multiple study items. Confirm time-sensitive rules with current FAA sources."
    },
    books: {
      completeRemotePilot: {
        title: "The Complete Remote Pilot, Second Edition", shortTitle: "Complete Remote Pilot",
        chapters: {
          "1": "Source pages 01–10 · UAS language and systems",
          "2": "Source pages 11–28 · applications, publications, and regulations",
          "3": "Source pages 29–42 · airspace and navigation (Lesson 3)"
        }
      }
    },
    sources, flashcards, questions
  };
})();
